### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/extends' from 'Benchmark.js'

### ISSUE THREAD

**Issue by gersonmontenegro** [paularmstrong/react-component-benchmark#3]
# Problem

yarn test fail.

**yarn test**

Here's code that shows what I'm doing:

```js
  test('Mount Main', () => {
    propsApp.component = Main;
    propsApp.onComplete = printOnCompleteResults.bind(this, 'Mounting FC Main');
    const component = mount(<Benchmark {...propsApp} />);
    component.instance().start();
  });
```

**Output**
```
yarn run v1.15.2
warning ../../../../package.json: No license field
$ jest
 FAIL  __tests__/App.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-runtime/helpers/extends' from 'Benchmark.js'

    However, Jest was able to find:
        './Benchmark.js'
        './Benchmark.js.flow'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 't
s', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (node_modules/react-component-benchmark/dist/Benchmark.js:9:40)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.519s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Here's what I expect to see when I run the above:

Success after execute test.

Any idea?

**Comment by paularmstrong** [comment]
This package probably needs to be updated to babel 7 and use `@babel/runtime`. Otherwise it needs a peerDependency of `babel-runtime`
